version: '3.9'

services:
  django:
    image: django-docker:0.0.1
    build: .
    ports:
      - "8000:8000"
    networks:
      - app_mynetwork

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user   
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app_mynetwork

volumes:
  mysql-data:

networks:
  app_mynetwork: